name: Generat e Podcas Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-lstest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Intall Dependecies
      run: |
        python -m pip intall --upgrade pip
        pip install pyyaml
    - name: Run Feed Generator
      run: python feed.py
    name: Push Repo
      run: |
        git config user.name github-actions
        git config user.email github-actuibs@hithub.com
        git add .
        git commit -m "Modified Feed"
        git push
    
